#!/bin/bash
# Blocks edits to sensitive files.
# Used as PreToolUse hook with Edit|Write matcher.
# Exit 0 = allow, Exit 2 = block (with stderr as feedback to Claude).

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

PROTECTED_PATTERNS=(
  ".env"
  ".env.local"
  ".env.production"
  "package-lock.json"
  "yarn.lock"
  "pnpm-lock.yaml"
  ".git/"
)

for pattern in "${PROTECTED_PATTERNS[@]}"; do
  if [[ "$FILE_PATH" == *"$pattern"* ]]; then
    echo "BLOCKED: '$FILE_PATH' is a protected file matching pattern '$pattern'. Do not edit this file directly. Use environment variables for secrets, and let package managers handle lock files." >&2
    exit 2
  fi
done

if [[ "$FILE_PATH" == *.generated.ts ]] || [[ "$FILE_PATH" == *.generated.js ]]; then
  echo "BLOCKED: '$FILE_PATH' is a generated file. Edit the corresponding .template.hbs file instead, then run 'npm run gen'." >&2
  exit 2
fi

exit 0
